name: Sync to Hugging Face Spaces
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hub
        uses: huggingface/hub-sync@v0.1.3
        with:
          github_repo_id: shahid-nawazai/Heart-Disease-Prediction-Live-Website
          huggingface_repo_id: shahid-nawazai/heart-disease-prediction
          hf_token: ${{ secrets.HF_TOKEN }}
